<script>
/* =====================================================================
   REGISTRO DE CONTENIDOS — ANAI BioLab
   Editable sin tocar la lógica. Cada estructura tiene 3 niveles de
   profundidad (n1 = 30 s, n2 = comprender, n3 = profundizar), relaciones
   CONECTA y una pregunta de comprobación.
   ===================================================================== */
window.BIO = window.BIO || {};

BIO.units = [
  {n:1, t:"La vida y su organización", d:"Características de los seres vivos, niveles de organización, método científico."},
  {n:2, t:"Biología celular", d:"Estructura y función de la célula; organelos; tipos celulares."},
  {n:3, t:"Metabolismo celular", d:"Respiración celular, fotosíntesis, enzimas, transporte."},
  {n:4, t:"Genética y biología molecular", d:"ADN, genes, herencia mendeliana, mutaciones."},
  {n:5, t:"Evolución", d:"Selección natural, evidencias, especiación."},
  {n:6, t:"Anatomía y fisiología humana", d:"Sistemas del cuerpo humano y su interconexión."},
  {n:7, t:"Ecología", d:"Ecosistemas, redes tróficas, ciclos, poblaciones."},
  {n:8, t:"Biodiversidad", d:"Clasificación, reinos, biodiversidad del Ecuador."},
  {n:9, t:"Biotecnología", d:"Aplicaciones, ingeniería genética, bioética."},
  {n:10, t:"Biología aplicada a problemas contemporáneos", d:"Salud, ambiente, cambio climático, alimentación."}
];

/* ---------- CORAZÓN: estructuras / hotspots ---------- */
BIO.heart = {
  id:"corazon", nombre:"Corazón humano", unidad:6, dominio:"anat",
  nota:"Modelo tridimensional simplificado con fines educativos. Proporciones y trayectos vasculares esquemáticos; sustituible por un modelo anatómico glTF definitivo.",
  structures:[
    {id:"auricula-derecha", nombre:"Aurícula derecha", capa:"camaras", color:"#8E3438", pos:[-1.12,0.62,-0.05], lbl:[-2.76,0.72,1.35], anchor:[-0.85,0.77,0.64],
      n1:"Cámara superior derecha. Recibe sangre pobre en oxígeno que regresa del cuerpo por las venas cavas.",
      n2:"Es una cámara de paredes delgadas porque solo necesita impulsar la sangre hacia el ventrículo derecho, situado justo debajo. Recibe sangre desoxigenada de la vena cava superior (cabeza y brazos), la vena cava inferior (tronco y piernas) y el seno coronario (el propio corazón). Cuando se contrae (sístole auricular), la sangre atraviesa la válvula tricúspide.",
      n3:"En su pared se localiza el nodo sinoauricular (nodo SA), el marcapasos natural: un grupo de células cardíacas especializadas que generan espontáneamente el impulso eléctrico que inicia cada latido (unos 60–100 impulsos por minuto en reposo). Por eso el latido comienza en las aurículas y se propaga hacia los ventrículos a través del nodo auriculoventricular.",
      dato:"Aquí nace cada latido: el nodo sinoauricular marca el ritmo del corazón.",
      conecta:["vena-cava-superior","vena-cava-inferior","valvula-tricuspide","ventriculo-derecho"], temas:["Sistema circulatorio","Homeostasis","Ritmo cardíaco"],
      quiz:{q:"¿Qué tipo de sangre recibe la aurícula derecha?", ops:["Sangre rica en oxígeno desde los pulmones","Sangre pobre en oxígeno que regresa del cuerpo","Sangre mezclada de ambos circuitos"], ok:1, fb:"La aurícula derecha recibe sangre desoxigenada de las venas cavas. La sangre oxigenada llega a la aurícula izquierda por las venas pulmonares."}},
    {id:"auricula-izquierda", nombre:"Aurícula izquierda", capa:"camaras", color:"#963A3C", pos:[0.7,0.8,-0.65], lbl:[3.98,1.02,-1.15], anchor:[0.84,1.05,-0.01],
      n1:"Cámara superior izquierda. Recibe sangre rica en oxígeno que llega de los pulmones por las venas pulmonares.",
      n2:"Cuatro venas pulmonares (dos por cada pulmón) desembocan en ella. Al contraerse, envía la sangre oxigenada al ventrículo izquierdo a través de la válvula mitral (bicúspide). Sus paredes son delgadas, como las de la aurícula derecha, porque el trayecto hasta el ventrículo es muy corto.",
      n3:"Las aurículas cumplen además una función endocrina: sus células liberan el péptido natriurético auricular (PNA) cuando se estiran por exceso de volumen, lo que estimula a los riñones a eliminar sodio y agua, ayudando a regular la presión arterial. Es un buen ejemplo de la conexión entre el sistema circulatorio, el endocrino y el urinario.",
      dato:"Es la única cámara que recibe sangre directamente desde los pulmones.",
      conecta:["venas-pulmonares","valvula-mitral","ventriculo-izquierdo"], temas:["Circulación pulmonar","Intercambio gaseoso"],
      quiz:{q:"¿Por qué vasos llega la sangre a la aurícula izquierda?", ops:["Venas cavas","Arteria pulmonar","Venas pulmonares"], ok:2, fb:"Las venas pulmonares son los únicos vasos del cuerpo llamados 'venas' que transportan sangre oxigenada: traen la sangre desde los pulmones hasta la aurícula izquierda."}},
    {id:"ventriculo-derecho", nombre:"Ventrículo derecho", capa:"camaras", color:"#A8443C", pos:[-0.35,-0.55,0.7], lbl:[-1.78,-2.22,1.6],
      n1:"Cámara inferior derecha. Bombea sangre pobre en oxígeno hacia los pulmones por la arteria pulmonar.",
      n2:"Recibe la sangre de la aurícula derecha y la impulsa a través de la válvula pulmonar hacia el tronco pulmonar. Su pared es más gruesa que la de las aurículas pero más delgada que la del ventrículo izquierdo, porque los pulmones están muy cerca y el circuito pulmonar ofrece poca resistencia.",
      n3:"La presión que genera el ventrículo derecho durante la sístole es de unos 25 mmHg, frente a los 120 mmHg del ventrículo izquierdo. Ambos ventrículos expulsan, sin embargo, el mismo volumen de sangre por latido (unos 70 mL en reposo): si no fuera así, la sangre se acumularía en uno de los dos circuitos. Este equilibrio se conoce como ley de Frank-Starling.",
      dato:"Bombea el mismo volumen que el ventrículo izquierdo, pero con cinco veces menos presión.",
      conecta:["auricula-derecha","valvula-pulmonar","arteria-pulmonar","tabique"], temas:["Circulación pulmonar","Presión arterial"],
      quiz:{q:"¿Hacia dónde envía la sangre el ventrículo derecho?", ops:["Hacia la aorta y todo el cuerpo","Hacia los pulmones por la arteria pulmonar","Hacia la aurícula izquierda"], ok:1, fb:"El ventrículo derecho impulsa la sangre desoxigenada a los pulmones a través de la válvula pulmonar y la arteria pulmonar."}},
    {id:"ventriculo-izquierdo", nombre:"Ventrículo izquierdo", capa:"camaras", color:"#9A3B34", pos:[0.8,-1.1,-0.2], lbl:[2.72,-2.25,0.58], anchor:[1.16,-0.86,0.83],
      n1:"Cámara inferior izquierda, la más musculosa. Bombea sangre oxigenada a todo el cuerpo por la aorta.",
      n2:"Su pared muscular (miocardio) es dos o tres veces más gruesa que la del ventrículo derecho porque debe generar presión suficiente para que la sangre llegue hasta los pies y el cerebro. Recibe sangre de la aurícula izquierda a través de la válvula mitral y la expulsa por la válvula aórtica.",
      n3:"El volumen que expulsa en cada latido (volumen sistólico, ~70 mL) multiplicado por la frecuencia cardíaca da el gasto cardíaco: unos 5 L/min en reposo, que puede superar los 20 L/min durante ejercicio intenso. El músculo cardíaco, a diferencia del esquelético, no se fatiga y se contrae de forma involuntaria y rítmica; sus células están unidas por discos intercalares que transmiten el impulso eléctrico de una a otra.",
      dato:"Su pared es hasta tres veces más gruesa que la del ventrículo derecho.",
      conecta:["auricula-izquierda","valvula-mitral","valvula-aortica","aorta","tabique"], temas:["Circulación sistémica","Presión arterial","Actividad física"],
      quiz:{q:"¿Por qué el ventrículo izquierdo tiene la pared más gruesa?", ops:["Porque recibe más sangre que el derecho","Porque debe generar más presión para impulsar la sangre a todo el cuerpo","Porque contiene el marcapasos del corazón"], ok:1, fb:"Ambos ventrículos bombean el mismo volumen; la diferencia está en la presión. El circuito sistémico es mucho más largo y resistente, así que el ventrículo izquierdo necesita más músculo."}},
    {id:"vena-cava-superior", nombre:"Vena cava superior", capa:"vasos", color:"#4A6FB5", pos:[-1.12,2.4,0.05], lbl:[-2.85,2.78,0.6],
      n1:"Gran vena que trae sangre pobre en oxígeno de la cabeza, el cuello y los brazos a la aurícula derecha.",
      n2:"Se forma por la unión de las venas braquiocefálicas. Al igual que la vena cava inferior, no tiene válvula en su desembocadura: la sangre entra en la aurícula derecha impulsada por la diferencia de presión y con ayuda de la respiración.",
      n3:"Las venas tienen paredes más delgadas y menos elásticas que las arterias, y su presión es muy baja (cerca de 0–5 mmHg cuando llegan al corazón). Por eso el retorno venoso depende de mecanismos auxiliares: la 'bomba muscular' de las piernas, las válvulas venosas y los cambios de presión torácica durante la inspiración.",
      dato:"La sangre de las venas cavas ha entregado su oxígeno y regresa cargada de CO₂.",
      conecta:["auricula-derecha","vena-cava-inferior"], temas:["Retorno venoso","Sistema circulatorio"],
      quiz:{q:"¿De qué regiones del cuerpo trae sangre la vena cava superior?", ops:["De las piernas y el abdomen","De la cabeza, el cuello y los brazos","De los pulmones"], ok:1, fb:"La cava superior drena la mitad superior del cuerpo; la cava inferior, la mitad inferior."}},
    {id:"vena-cava-inferior", nombre:"Vena cava inferior", capa:"vasos", color:"#4A6FB5", pos:[-1.2,-0.9,-0.4], lbl:[-2.5,-1.86,0.3], anchor:[-1.25,-1.9,-0.2],
      n1:"Gran vena que trae sangre pobre en oxígeno del tronco, el abdomen y las piernas a la aurícula derecha.",
      n2:"Es la vena de mayor diámetro del cuerpo. Recoge la sangre de las venas ilíacas, renales y hepáticas, entre otras, y entra en la aurícula derecha por su parte inferior.",
      n3:"Antes de llegar al corazón, la sangre de los intestinos pasa primero por el hígado a través de la vena porta (sistema porta hepático), donde se filtran y procesan los nutrientes absorbidos. Luego las venas hepáticas la vierten en la cava inferior. Es un ejemplo de conexión directa entre el sistema digestivo y el circulatorio.",
      dato:"Es la vena más ancha del cuerpo humano.",
      conecta:["auricula-derecha","vena-cava-superior"], temas:["Retorno venoso","Sistema digestivo"],
      quiz:{q:"La sangre de la vena cava inferior es…", ops:["rica en oxígeno","pobre en oxígeno y rica en CO₂","igual a la de la aorta"], ok:1, fb:"Toda la sangre que llega por las cavas ya entregó oxígeno a los tejidos y transporta el CO₂ producido por la respiración celular."}},
    {id:"arteria-pulmonar", nombre:"Arteria pulmonar", capa:"vasos", color:"#3E63B8", pos:[0.42,1.3,0.52], lbl:[3.17,2.15,-0.68],
      n1:"Lleva sangre pobre en oxígeno desde el ventrículo derecho hasta los pulmones. Es la única arteria con sangre desoxigenada.",
      n2:"Sale del ventrículo derecho como tronco pulmonar y se divide en arteria pulmonar derecha e izquierda, una para cada pulmón. Se llama 'arteria' porque sale del corazón, no por el tipo de sangre que transporta: las arterias siempre alejan la sangre del corazón y las venas siempre la devuelven.",
      n3:"Dentro de los pulmones se ramifica hasta formar capilares que rodean los alvéolos; allí el CO₂ difunde hacia el aire alveolar y el O₂ hacia la sangre. La presión en la circulación pulmonar es baja (~25/8 mmHg), lo que evita que el plasma se filtre hacia los alvéolos y los inunde.",
      dato:"Es la excepción de la regla: una arteria con sangre pobre en oxígeno.",
      conecta:["ventriculo-derecho","valvula-pulmonar","venas-pulmonares"], temas:["Circulación pulmonar","Intercambio gaseoso","Respiración"],
      quiz:{q:"¿Por qué la arteria pulmonar se llama 'arteria' aunque transporta sangre desoxigenada?", ops:["Porque tiene paredes musculares gruesas","Porque sale del corazón: las arterias siempre alejan la sangre del corazón","Porque conecta con la aorta"], ok:1, fb:"Arteria y vena se definen por la dirección del flujo respecto al corazón, no por el contenido de oxígeno."}},
    {id:"venas-pulmonares", nombre:"Venas pulmonares", capa:"vasos", color:"#C8322E", pos:[1.9,1.2,-0.9], lbl:[3.84,1.44,-1.66],
      n1:"Cuatro venas que traen sangre rica en oxígeno desde los pulmones hasta la aurícula izquierda.",
      n2:"Dos salen de cada pulmón. Son las únicas venas del cuerpo que transportan sangre oxigenada, porque acaban de recoger el oxígeno captado en los alvéolos.",
      n3:"La sangre que sale de los pulmones tiene una saturación de oxígeno cercana al 97–99 %: casi todas las moléculas de hemoglobina de los glóbulos rojos llevan cuatro moléculas de O₂ unidas. Al pasar por los tejidos la saturación baja a ~70–75 % en reposo, y mucho más durante el ejercicio intenso.",
      dato:"Son las únicas venas con sangre oxigenada.",
      conecta:["auricula-izquierda","arteria-pulmonar"], temas:["Circulación pulmonar","Hemoglobina"],
      quiz:{q:"¿Qué tienen de especial las venas pulmonares?", ops:["Son las únicas venas que llevan sangre oxigenada","Son las venas más largas del cuerpo","Tienen válvulas que impiden el retorno"], ok:0, fb:"Recogen la sangre recién oxigenada en los alvéolos y la conducen a la aurícula izquierda."}},
    {id:"aorta", nombre:"Aorta", capa:"vasos", color:"#C8322E", pos:[-0.3,2.3,0.05], lbl:[-1.64,3.9,0.17],
      n1:"La arteria más grande del cuerpo. Distribuye la sangre oxigenada desde el ventrículo izquierdo a todos los órganos.",
      n2:"Sale del ventrículo izquierdo, forma un arco (cayado aórtico) del que nacen las arterias hacia la cabeza y los brazos, y desciende por el tórax y el abdomen dando ramas a todos los órganos. Sus paredes son gruesas y elásticas para soportar la alta presión de cada latido.",
      n3:"La elasticidad de la aorta funciona como un amortiguador: se distiende en la sístole y se retrae en la diástole, manteniendo el flujo continuo aunque el corazón bombee a pulsos. Con la edad o por hábitos poco saludables las arterias pueden endurecerse (arteriosclerosis), lo que eleva la presión arterial y sobrecarga el ventrículo izquierdo.",
      dato:"Tiene unos 2,5 cm de diámetro y sus paredes son elásticas.",
      conecta:["ventriculo-izquierdo","valvula-aortica","vasos-coronarios"], temas:["Circulación sistémica","Presión arterial","Homeostasis"],
      quiz:{q:"¿Qué tipo de sangre transporta la aorta?", ops:["Sangre oxigenada hacia los tejidos","Sangre desoxigenada hacia los pulmones","Sangre desoxigenada hacia el corazón"], ok:0, fb:"La aorta recibe la sangre del ventrículo izquierdo, que acaba de llegar oxigenada desde los pulmones, y la reparte a todo el cuerpo."}},
    {id:"valvula-tricuspide", nombre:"Válvula tricúspide", capa:"valvulas", color:"#E8DCCB", pos:[-0.85,0.02,0.2], lbl:[-2.85,-1,1.16],
      n1:"Válvula de tres valvas entre la aurícula derecha y el ventrículo derecho. Impide que la sangre retroceda.",
      n2:"Se abre cuando la aurícula se contrae y se cierra cuando el ventrículo se contrae, de modo que la sangre solo puede avanzar hacia la arteria pulmonar. Su cierre produce el primer ruido cardíaco ('lub').",
      n3:"Las valvas están sujetas por cuerdas tendinosas a los músculos papilares de la pared ventricular; estos se contraen junto con el ventrículo para que la válvula no se invierta hacia la aurícula. Cuando una válvula no cierra bien se produce un soplo cardíaco, un sonido audible con el estetoscopio.",
      dato:"El cierre de las válvulas auriculoventriculares produce el sonido 'lub'.",
      conecta:["auricula-derecha","ventriculo-derecho"], temas:["Ciclo cardíaco","Ruidos cardíacos"],
      quiz:{q:"¿Cuál es la función principal de las válvulas cardíacas?", ops:["Generar el impulso eléctrico","Impedir que la sangre retroceda","Oxigenar la sangre"], ok:1, fb:"Las válvulas garantizan un flujo en un solo sentido; el impulso lo genera el nodo sinoauricular y la oxigenación ocurre en los pulmones."}},
    {id:"valvula-mitral", nombre:"Válvula mitral (bicúspide)", capa:"valvulas", color:"#E8DCCB", pos:[0.62,0.05,-0.35], lbl:[3.34,-0.21,-1.28],
      n1:"Válvula de dos valvas entre la aurícula izquierda y el ventrículo izquierdo.",
      n2:"Funciona igual que la tricúspide: se abre durante el llenado del ventrículo y se cierra durante su contracción, evitando que la sangre regrese a la aurícula izquierda y a los pulmones.",
      n3:"Es la válvula que soporta mayor presión, porque el ventrículo izquierdo genera unos 120 mmHg. Su nombre proviene de la mitra, el gorro de dos puntas de los obispos. La estenosis mitral (estrechamiento) y la insuficiencia mitral (cierre incompleto) son alteraciones frecuentes.",
      dato:"Es la única válvula del corazón con solo dos valvas.",
      conecta:["auricula-izquierda","ventriculo-izquierdo"], temas:["Ciclo cardíaco"],
      quiz:{q:"¿Entre qué cámaras se encuentra la válvula mitral?", ops:["Aurícula derecha y ventrículo derecho","Aurícula izquierda y ventrículo izquierdo","Ventrículo izquierdo y aorta"], ok:1, fb:"La mitral separa las cámaras izquierdas; entre el ventrículo izquierdo y la aorta está la válvula aórtica."}},
    {id:"valvula-pulmonar", nombre:"Válvula pulmonar", capa:"valvulas", color:"#E8DCCB", pos:[0.3,0.62,0.72], lbl:[-2.41,0.22,1.99], anchor:[0.36,0.6,0.89],
      n1:"Válvula semilunar entre el ventrículo derecho y la arteria pulmonar.",
      n2:"Tiene tres valvas en forma de media luna. Se abre cuando el ventrículo derecho se contrae y se cierra cuando se relaja, para que la sangre de la arteria pulmonar no regrese al ventrículo.",
      n3:"El cierre simultáneo de las válvulas pulmonar y aórtica produce el segundo ruido cardíaco ('dub'). A diferencia de las válvulas auriculoventriculares, las semilunares no tienen cuerdas tendinosas: se cierran pasivamente cuando la presión del vaso supera la del ventrículo.",
      dato:"Las válvulas semilunares se cierran solas cuando la presión del vaso supera la del ventrículo.",
      conecta:["ventriculo-derecho","arteria-pulmonar"], temas:["Ciclo cardíaco"],
      quiz:{q:"¿Cuándo se cierra la válvula pulmonar?", ops:["Cuando el ventrículo derecho se contrae","Cuando el ventrículo derecho se relaja","Cuando la aurícula derecha se contrae"], ok:1, fb:"Al relajarse el ventrículo, la presión en la arteria pulmonar es mayor y empuja las valvas hasta cerrarlas."}},
    {id:"valvula-aortica", nombre:"Válvula aórtica", capa:"valvulas", color:"#E8DCCB", pos:[0.1,0.38,-0.1], lbl:[-2.34,-0.53,1],
      n1:"Válvula semilunar entre el ventrículo izquierdo y la aorta.",
      n2:"Se abre cuando el ventrículo izquierdo se contrae y expulsa la sangre a la aorta; se cierra al relajarse el ventrículo, evitando que la sangre regrese.",
      n3:"Justo por encima de la válvula aórtica nacen las arterias coronarias, que irrigan al propio músculo cardíaco. Se llenan sobre todo durante la diástole, cuando la válvula está cerrada y la presión de la aorta empuja la sangre hacia ellas. La obstrucción de una arteria coronaria provoca un infarto de miocardio.",
      dato:"Sobre esta válvula nacen las arterias coronarias que alimentan al corazón.",
      conecta:["ventriculo-izquierdo","aorta","vasos-coronarios"], temas:["Ciclo cardíaco","Salud cardiovascular"],
      quiz:{q:"¿Qué ocurriría si la válvula aórtica no cerrara bien?", ops:["La sangre regresaría al ventrículo izquierdo durante la diástole","La sangre pasaría al ventrículo derecho","No pasaría nada porque la aorta es elástica"], ok:0, fb:"Sin un cierre correcto, parte de la sangre expulsada retorna al ventrículo (insuficiencia aórtica), reduciendo la eficiencia de cada latido."}},
    {id:"vasos-coronarios", nombre:"Vasos coronarios", capa:"vasos", color:"#C8463C", pos:[0.4,-0.6,1.15], lbl:[3.03,-1.14,0.31],
      n1:"Arterias y venas que recorren la superficie del corazón y alimentan al propio músculo cardíaco. Van acompañadas de grasa epicárdica.",
      n2:"Las arterias coronarias derecha e izquierda nacen de la aorta, justo por encima de la válvula aórtica. La izquierda se divide en la descendente anterior, que baja por el surco entre los dos ventrículos, y la circunfleja, que rodea el corazón por el surco auriculoventricular. Las venas cardíacas recogen la sangre ya usada y la vierten en el seno coronario, que desemboca en la aurícula derecha.",
      n3:"El corazón pesa unos 300 g, pero recibe cerca del 5 % del gasto cardíaco. Las coronarias se llenan sobre todo durante la diástole, porque en la sístole el músculo contraído las comprime. Si una placa de ateroma obstruye una arteria coronaria, el músculo que depende de ella queda sin oxígeno: es el infarto de miocardio. La grasa amarillenta de los surcos es normal y rodea y protege a los vasos.",
      dato:"El corazón no se alimenta de la sangre que pasa por sus cavidades, sino de sus propias arterias.",
      conecta:["aorta","valvula-aortica","ventriculo-izquierdo","auricula-derecha"], temas:["Infarto de miocardio","Salud cardiovascular","Irrigación"],
      quiz:{q:"¿Por qué la obstrucción de una arteria coronaria causa un infarto?", ops:["Porque impide que la sangre salga del corazón hacia el cuerpo","Porque una parte del músculo cardíaco deja de recibir oxígeno","Porque las válvulas dejan de cerrarse"], ok:1, fb:"El miocardio depende de las coronarias para recibir O₂; sin él, sus células mueren.", wrong:["La sangre sigue saliendo por la aorta; el problema es la irrigación del propio músculo.","Las válvulas no son el problema principal: el daño es la muerte del músculo sin oxígeno."]}},
    {id:"tabique", nombre:"Tabique interventricular", capa:"camaras", color:"#7E2C2A", pos:[0.2,-0.85,0.25], lbl:[-0.1,-2.62,0.85], interno:true,
      n1:"Pared muscular que separa completamente el ventrículo derecho del izquierdo.",
      n2:"Gracias al tabique, la sangre desoxigenada del lado derecho nunca se mezcla con la sangre oxigenada del lado izquierdo. Existe también un tabique interauricular entre las dos aurículas.",
      n3:"Antes del nacimiento, el tabique interauricular tiene un orificio (foramen oval) que permite a la sangre saltarse los pulmones, que aún no funcionan. Normalmente se cierra tras el primer llanto. Si el tabique interventricular no se cierra por completo, queda una comunicación interventricular, una de las cardiopatías congénitas más frecuentes.",
      dato:"Impide que se mezclen la sangre oxigenada y la desoxigenada.",
      conecta:["ventriculo-derecho","ventriculo-izquierdo"], temas:["Circulación doble","Desarrollo embrionario"],
      quiz:{q:"¿Qué consecuencia tendría una abertura en el tabique interventricular?", ops:["Se mezclaría sangre oxigenada con desoxigenada","El corazón latiría más despacio","La sangre no llegaría a los pulmones"], ok:0, fb:"Parte de la sangre oxigenada pasaría del ventrículo izquierdo al derecho (mayor presión → menor presión), mezclándose y reduciendo el oxígeno que llega a los tejidos."}}
  ],
  capas:[{id:"camaras",n:"Cámaras"},{id:"vasos",n:"Vasos"},{id:"valvulas",n:"Válvulas"}],
  guiada:[
    {tipo:"select", target:"auricula-derecha", txt:"Localiza y selecciona la <b>aurícula derecha</b>. Pista: está en la parte superior, del lado por el que llegan las venas cavas (a tu izquierda en la vista frontal)."},
    {tipo:"select", target:"ventriculo-derecho", txt:"Ahora identifica el <b>ventrículo derecho</b>. Los ventrículos ocupan la región inferior del corazón."},
    {tipo:"anim", target:"flujo", txt:"Activa el <b>flujo sanguíneo</b> (Animación → Flujo sanguíneo) y observa con qué color circula la sangre por el lado derecho y por el izquierdo."},
    {tipo:"select", target:"arteria-pulmonar", txt:"Selecciona el vaso por el que <b>sale</b> la sangre del ventrículo derecho."},
    {tipo:"select", target:"ventriculo-izquierdo", txt:"Selecciona la cámara con la <b>pared más gruesa</b>."},
    {tipo:"text", txt:"Explica con tus palabras el recorrido de una gota de sangre desde que entra por la vena cava hasta que sale por la aorta. Menciona las cuatro cámaras. Tu respuesta se guardará en el cuaderno."}
  ]
};

/* ---------- CÉLULA ANIMAL: organelos ---------- */
BIO.cell = {
  id:"celula-animal", nombre:"Célula animal", unidad:2, dominio:"cell",
  nota:"Modelo tridimensional simplificado con fines educativos. Tamaños relativos exagerados para facilitar la visualización.",
  structures:[
    {id:"membrana", nombre:"Membrana plasmática", color:"#5FB8C4",
      funcion:"Delimita la célula, controla qué entra y qué sale (permeabilidad selectiva) y permite la comunicación con otras células.",
      estructura:"Bicapa de fosfolípidos con proteínas insertadas (modelo de mosaico fluido), colesterol y glúcidos en la cara externa.",
      relaciones:"Trabaja con el citoesqueleto (forma), las vesículas del Golgi (secreción) y los receptores hormonales (comunicación).",
      analogia:"Como la puerta con portero de un edificio: deja pasar a quien tiene permiso y detiene al resto.",
      n3:"El transporte pasivo (difusión, ósmosis, difusión facilitada) no gasta energía; el transporte activo usa ATP para mover sustancias contra su gradiente, como la bomba de sodio-potasio, que consume cerca de un tercio de la energía de una célula nerviosa.",
      accion:{t:"Transporte de sustancias", d:"Moléculas pequeñas cruzan la membrana por difusión; otras entran por canales o transportadores."}},
    {id:"citoplasma", nombre:"Citoplasma", color:"#A9D6DC",
      funcion:"Medio acuoso donde se encuentran los organelos y ocurren muchas reacciones químicas, como la glucólisis.",
      estructura:"Citosol (agua, iones, proteínas, azúcares) atravesado por una red de filamentos: el citoesqueleto.",
      relaciones:"Conecta todos los organelos; el citoesqueleto mueve vesículas y organelos y da forma a la célula.",
      analogia:"Como el aire y los pasillos de una fábrica: el espacio por el que todo circula.",
      n3:"El citoesqueleto está formado por microfilamentos de actina, filamentos intermedios y microtúbulos de tubulina. Los microtúbulos sirven de 'rieles' para proteínas motoras (cinesina, dineína) que transportan cargas por la célula.",
      accion:{t:"Glucólisis", d:"La glucosa se rompe en dos moléculas de piruvato en el citosol, obteniendo un poco de ATP antes de entrar a la mitocondria."}},
    {id:"nucleo", nombre:"Núcleo", color:"#6A58C7",
      funcion:"Guarda la información genética (ADN) y controla la actividad celular: qué proteínas se fabrican y cuándo.",
      estructura:"Rodeado por una envoltura doble con poros nucleares. Contiene la cromatina (ADN + proteínas) y el nucléolo.",
      relaciones:"Envía ARN mensajero a los ribosomas; recibe señales del citoplasma; se duplica y divide en la mitosis.",
      analogia:"Como la biblioteca de planos de una fábrica: los planos no salen, se copian.",
      n3:"El ADN humano mide unos 2 metros por célula y cabe en un núcleo de ~6 µm gracias a que se enrolla en proteínas llamadas histonas. Durante la división celular la cromatina se compacta hasta formar los 46 cromosomas visibles al microscopio.",
      accion:{t:"Transcripción", d:"Un gen se copia en ARN mensajero, que sale por los poros nucleares hacia los ribosomas."}},
    {id:"nucleolo", nombre:"Nucléolo", color:"#4B3D9C",
      funcion:"Fabrica los componentes de los ribosomas (ARN ribosómico y proteínas).",
      estructura:"Región densa dentro del núcleo, sin membrana propia.",
      relaciones:"Sus productos salen por los poros nucleares y se ensamblan en ribosomas en el citoplasma.",
      analogia:"El taller donde se construyen las máquinas que después fabricarán las proteínas.",
      n3:"Las células que producen muchas proteínas (por ejemplo, las del páncreas) tienen nucléolos grandes y muy activos. Un núcleo puede tener más de un nucléolo.",
      accion:{t:"Ensamblaje de ribosomas", d:"Subunidades ribosómicas salen del núcleo y se unen en el citoplasma."}},
    {id:"mitocondria", nombre:"Mitocondria", color:"#E07A4F",
      funcion:"Produce la mayor parte del ATP de la célula mediante la respiración celular.",
      estructura:"Doble membrana: la externa lisa y la interna plegada en crestas, que aumentan la superficie donde ocurre la cadena de transporte de electrones. Tiene su propio ADN.",
      relaciones:"Recibe piruvato del citoplasma y oxígeno de la sangre; libera CO₂ y ATP que usan todos los procesos celulares.",
      analogia:"La central eléctrica: transforma el combustible (glucosa) en energía utilizable (ATP).",
      n3:"Las mitocondrias tienen su propio ADN circular y ribosomas parecidos a los bacterianos: según la teoría endosimbiótica, descienden de bacterias que fueron incorporadas por células ancestrales hace ~1.500 millones de años. Se heredan casi exclusivamente por vía materna.",
      accion:{t:"Respiración celular", d:"Glucosa + O₂ → CO₂ + H₂O + ATP. Las crestas concentran las enzimas de la cadena respiratoria."}},
    {id:"ribosomas", nombre:"Ribosomas", color:"#3A3A4A",
      funcion:"Sintetizan proteínas leyendo la información del ARN mensajero (traducción).",
      estructura:"Dos subunidades de ARN ribosómico y proteínas; sin membrana. Pueden estar libres o unidos al retículo endoplasmático.",
      relaciones:"Reciben ARNm del núcleo y aminoácidos transportados por ARNt; sus proteínas van al citosol o al retículo.",
      analogia:"Las impresoras 3D de la célula: leen el código y construyen la proteína.",
      n3:"Un ribosoma humano lee unos 6 codones por segundo. Varios ribosomas pueden leer el mismo ARNm a la vez formando un polirribosoma. Muchos antibióticos actúan bloqueando los ribosomas bacterianos, que son distintos de los nuestros.",
      accion:{t:"Traducción", d:"El ribosoma recorre el ARNm y une aminoácidos según cada codón, formando una proteína."}},
    {id:"rer", nombre:"Retículo endoplasmático rugoso", color:"#7FA7C9",
      funcion:"Sintetiza y pliega proteínas destinadas a la membrana, a los lisosomas o a ser secretadas fuera de la célula.",
      estructura:"Red de sacos membranosos aplanados (cisternas) conectados con la envoltura nuclear y con ribosomas adheridos en su superficie.",
      relaciones:"Envía las proteínas en vesículas al aparato de Golgi.",
      analogia:"La línea de ensamblaje y control de calidad de una fábrica.",
      n3:"Las proteínas que entran al RER llevan una 'señal de dirección' (péptido señal) en su extremo inicial. Dentro del retículo se pliegan con ayuda de chaperonas y reciben azúcares (glicosilación). Las mal plegadas se destruyen.",
      accion:{t:"Síntesis de proteínas de secreción", d:"Los ribosomas del RER introducen la proteína en la cisterna; luego sale en vesículas hacia el Golgi."}},
    {id:"rel", nombre:"Retículo endoplasmático liso", color:"#9CC1DD",
      funcion:"Sintetiza lípidos, elimina toxinas y almacena calcio.",
      estructura:"Red de túbulos membranosos sin ribosomas, continua con el rugoso.",
      relaciones:"Provee los lípidos para todas las membranas de la célula; en las células musculares libera calcio para la contracción.",
      analogia:"El almacén de materiales y la planta de tratamiento de residuos.",
      n3:"Las células del hígado tienen mucho retículo liso porque metabolizan medicamentos y alcohol. Con el consumo repetido de ciertas sustancias el REL aumenta de tamaño (tolerancia).",
      accion:{t:"Síntesis de lípidos", d:"Los fosfolípidos se forman en la membrana del REL y se distribuyen por vesículas."}},
    {id:"golgi", nombre:"Aparato de Golgi", color:"#D9A441",
      funcion:"Modifica, clasifica y empaqueta proteínas y lípidos, y los envía a su destino en vesículas.",
      estructura:"Pila de sacos membranosos aplanados (cisternas) con una cara de entrada (cis) y una de salida (trans).",
      relaciones:"Recibe vesículas del retículo; forma lisosomas y vesículas de secreción que viajan a la membrana.",
      analogia:"La oficina de correos: etiqueta cada paquete con su dirección y lo despacha.",
      n3:"Las modificaciones del Golgi (añadir o recortar azúcares, fosfatos, etc.) actúan como 'códigos postales' moleculares. Por ejemplo, las enzimas que llevan manosa-6-fosfato son enviadas a los lisosomas.",
      accion:{t:"Secreción", d:"Una vesícula se desprende de la cara trans, viaja por el citoesqueleto y se fusiona con la membrana (exocitosis)."}},
    {id:"lisosomas", nombre:"Lisosomas", color:"#C25B8A",
      funcion:"Digieren moléculas, organelos viejos y partículas que la célula captura, gracias a enzimas digestivas.",
      estructura:"Vesículas esféricas rodeadas de membrana con interior ácido (pH ~4,5) y unas 50 enzimas hidrolíticas.",
      relaciones:"Se forman en el Golgi; se fusionan con vesículas de endocitosis y con organelos dañados (autofagia).",
      analogia:"El centro de reciclaje: descompone lo que ya no sirve en piezas reutilizables.",
      n3:"El interior ácido protege a la célula: si una enzima escapa al citosol (pH ~7,2) queda casi inactiva. Los glóbulos blancos usan lisosomas para destruir bacterias fagocitadas. Fallos en enzimas lisosómicas causan enfermedades de acumulación como la de Tay-Sachs.",
      accion:{t:"Digestión celular", d:"El lisosoma se fusiona con una vesícula que contiene una partícula y la degrada."}},
    {id:"centriolos", nombre:"Centríolos", color:"#5B7C99",
      funcion:"Organizan los microtúbulos y forman el huso mitótico que separa los cromosomas durante la división celular.",
      estructura:"Dos cilindros perpendiculares formados por nueve tripletes de microtúbulos, situados cerca del núcleo (centrosoma).",
      relaciones:"Se duplican antes de la mitosis; el huso conecta con los cromosomas.",
      analogia:"Las grúas que reparten los cromosomas entre las dos células hijas.",
      n3:"Las células vegetales no tienen centríolos, pero forman el huso mitótico igualmente. Los centríolos también dan origen a los cilios y flagelos (por ejemplo, el flagelo del espermatozoide).",
      accion:{t:"Formación del huso", d:"Los centríolos migran a polos opuestos y emiten microtúbulos hacia los cromosomas."}}
  ]
};

/* ---------- MISIONES ---------- */
BIO.missions = [
  {id:"globulo-rojo", t:"El viaje de un glóbulo rojo", d:"Sigue a un eritrocito por la circulación doble y comprende cómo se conectan los sistemas circulatorio y respiratorio.", unidad:6, dominio:"anat", xp:150, disponible:true, em:"🩸", dur:"15–20 min"},
  {id:"salva-celula", t:"Salva la célula", d:"Una célula no produce suficiente energía. Detecta qué organelo está fallando a partir de las evidencias.", unidad:2, dominio:"cell", xp:120, disponible:false, em:"🔬", dur:"12 min"},
  {id:"ecosistema-riesgo", t:"El ecosistema en riesgo", d:"Una población colapsa en un manglar ecuatoriano. Identifica la causa del desequilibrio.", unidad:7, dominio:"eco", xp:140, disponible:false, em:"🌱", dur:"15 min"},
  {id:"codigo-genetico", t:"Código genético", d:"Resuelve un problema de herencia y predice el fenotipo de la descendencia.", unidad:4, dominio:"gen", xp:130, disponible:false, em:"🧬", dur:"12 min"},
  {id:"diagnostico-celular", t:"Diagnóstico celular", d:"Identifica una anomalía celular observando muestras al microscopio virtual.", unidad:2, dominio:"cell", xp:120, disponible:false, em:"🧪", dur:"10 min"}
];

BIO.badges = [
  {id:"explorador-celular", em:"🔬", n:"Explorador Celular", d:"Explora los 11 componentes de la célula animal."},
  {id:"anatomista", em:"🫀", n:"Anatomista", d:"Explora todas las estructuras del corazón."},
  {id:"viajero", em:"🩸", n:"Viajero sanguíneo", d:"Completa la misión del glóbulo rojo."},
  {id:"investigador", em:"🧪", n:"Investigador", d:"Completa un laboratorio con hipótesis y conclusión."},
  {id:"genetista", em:"🧬", n:"Genetista", d:"Resuelve un problema de herencia."},
  {id:"ecologo", em:"🌱", n:"Ecólogo", d:"Analiza una red alimentaria."},
  {id:"neuroexplorador", em:"🧠", n:"Neuroexplorador", d:"Sigue un impulso nervioso."}
];

/* Contribución de cada actividad al progreso por unidad (0–100) */
BIO.activities = {
  "explorar-corazon":{t:"Explorar el corazón", unidad:6, peso:25, xp:60},
  "guiada-corazon":{t:"Exploración guiada del corazón", unidad:6, peso:15, xp:80},
  "explorar-celula":{t:"Explorar la célula animal", unidad:2, peso:20, xp:60},
  "mision-globulo":{t:"Misión: El viaje de un glóbulo rojo", unidad:6, peso:30, xp:150},
  "lab-fotosintesis":{t:"Laboratorio: Fotosíntesis", unidad:3, peso:30, xp:120},
  "sim-circulacion":{t:"Simulador cardiorrespiratorio", unidad:6, peso:10, xp:40},
  "eval-corazon":{t:"Evaluación: el corazón", unidad:6, peso:20, xp:100}
};

/* Datos ficticios de grupo para el panel docente (no corresponden a personas reales) */
BIO.teacherClass = {
  curso:"1.º BGU · Paralelo A", docente:"Docente de Biología",
  estudiantes:[
    {n:"Valentina Cobo", p:71, act:9, t:212, m:2, l:2, err:1},
    {n:"Sebastián Ríos", p:58, act:7, t:164, m:1, l:1, err:3},
    {n:"Camila Ortiz", p:82, act:11, t:248, m:2, l:2, err:0},
    {n:"Nicolás Paredes", p:34, act:4, t:96, m:0, l:1, err:4},
    {n:"Isabella Mora", p:66, act:8, t:190, m:1, l:2, err:2},
    {n:"Emilio Vaca", p:45, act:5, t:121, m:1, l:1, err:3},
    {n:"Doménica Salas", p:77, act:10, t:230, m:2, l:2, err:1},
    {n:"Joaquín Torres", p:29, act:3, t:74, m:0, l:0, err:5},
    {n:"Martina Vélez", p:63, act:8, t:178, m:1, l:1, err:2},
    {n:"Andrés Cedeño", p:52, act:6, t:140, m:1, l:1, err:3},
    {n:"Rafaela Ponce", p:88, act:12, t:265, m:2, l:2, err:0}
  ],
  preguntasError:[
    {q:"Selecciona el ventrículo izquierdo (3D)", err:41, concepto:"Lateralidad anatómica"},
    {q:"¿Por qué la arteria pulmonar lleva sangre desoxigenada?", err:38, concepto:"Arteria vs. vena"},
    {q:"Ordena el recorrido de la sangre", err:33, concepto:"Circulación doble"},
    {q:"Variable controlada en el laboratorio de fotosíntesis", err:29, concepto:"Control de variables"},
    {q:"Función del aparato de Golgi", err:22, concepto:"Organelos"},
    {q:"¿Qué sucede con la saturación de O₂ en los tejidos?", err:18, concepto:"Intercambio gaseoso"}
  ],
  unidades:[{u:1,p:92},{u:2,p:74},{u:3,p:48},{u:4,p:21},{u:6,p:57}]
};
</script>
