<script>
/* =====================================================================
   CIENCIAS NATURALES · EGB SUPERIOR (8.º, 9.º y 10.º)
   Transcripción del Ecosistema Curricular ANAI Online 2027–2028,
   Área 3 · Tronco común. Dos dominios: Ciencias de la Vida y la Tierra
   (CVT) y Ciencias Físicas (CF). Tres unidades por dominio y grado.
   ===================================================================== */

/* ---------- Programas y niveles ---------- */
BIO.programas = {
  bio: { id:'bio', n:'Biología', sub:'Bachillerato', em:'🧬', dom:'anat', home:'#/', d:'Laboratorio virtual de Biología para 1.º, 2.º y 3.º de Bachillerato.' },
  cn:  { id:'cn',  n:'Ciencias Naturales', sub:'EGB Superior', em:'🔬', dom:'eco', home:'#/cn', d:'Ciencias de la Vida y la Tierra + Ciencias Físicas para 8.º, 9.º y 10.º de EGB.' }
};
BIO.niveles = [
  { id:8,  corto:'8.º EGB',  n:'8.º de EGB Superior', prog:'cn',  d:'Fundamenta: consolida lenguaje científico, medición y modelos; explica con evidencia.' },
  { id:9,  corto:'9.º EGB',  n:'9.º de EGB Superior', prog:'cn',  d:'Conecta: relaciona variables, sistemas y fuentes; selecciona modelos y contrasta evidencia.' },
  { id:10, corto:'10.º EGB', n:'10.º de EGB Superior', prog:'cn', d:'Transfiere: modela problemas, evalúa límites y defiende decisiones con autonomía.' },
  { id:1,  corto:'1.º BGU',  n:'1.º de Bachillerato', prog:'bio', d:'La vida y su organización, la célula y el metabolismo celular.' },
  { id:2,  corto:'2.º BGU',  n:'2.º de Bachillerato', prog:'bio', d:'Genética, evolución y anatomía y fisiología humana.' },
  { id:3,  corto:'3.º BGU',  n:'3.º de Bachillerato', prog:'bio', d:'Ecología, biodiversidad, biotecnología y biología aplicada.' }
];
BIO.nivel = id => BIO.niveles.find(n => n.id === +id) || BIO.niveles[3];
BIO.progOf = nivel => BIO.nivel(nivel).prog;
BIO.nivelesDe = prog => BIO.niveles.filter(n => n.prog === prog);

/* ---------- Dominios y competencias del área ---------- */
BIO.cn = {
  proposito:'Mantener la unidad oficial de Ciencias Naturales y, desde 8.º EGB, hacer visible una especialización progresiva. Ciencias de la Vida y la Tierra estudia sistemas vivos, salud, biodiversidad, geología y clima; Ciencias Físicas desarrolla medición, materia, movimiento, energía, ondas, electricidad y modelización.',
  enfoque:'Ciclo pregunta–modelo–evidencia–explicación; laboratorios virtuales o prácticas seguras; análisis de datos; argumentación CER; resolución de problemas y comunicación de incertidumbre.',
  dominios: [
    { id:'cvt', n:'Ciencias de la Vida y la Tierra', corto:'Vida y Tierra', em:'🌱', dom:'eco', d:'Sistemas vivos, salud, biodiversidad, geología y clima.' },
    { id:'cf',  n:'Ciencias Físicas', corto:'Físicas', em:'⚛️', dom:'gen', d:'Medición, materia, movimiento, energía, ondas, electricidad y modelización.' }
  ],
  competencias: [
    { c:'AO-CN-1',  n:'Indagación y evidencia', d:'Formula preguntas, diseña indagaciones seguras, analiza datos, contrasta modelos y revisa explicaciones.' },
    { c:'AO-CVT-1', n:'Vida, organización y evolución', d:'Explica organización, herencia, salud e interdependencia de los seres vivos.' },
    { c:'AO-CVT-2', n:'Tierra, clima y sostenibilidad', d:'Interpreta procesos terrestres y climáticos y evalúa riesgos y decisiones ambientales.' },
    { c:'AO-CF-1',  n:'Modelización, movimiento y energía', d:'Mide, representa y usa modelos cuantitativos para explicar movimiento, fuerzas y transferencias de energía.' },
    { c:'AO-CF-2',  n:'Materia, ondas, campos y tecnología', d:'Relaciona propiedades de la materia, señales, circuitos y campos con aplicaciones y límites tecnológicos.' }
  ],
  progresion: [
    { id:8,  t:'Fundamenta', d:'Construye lenguaje disciplinar, medición y modelos; distingue observación, dato y explicación.' },
    { id:9,  t:'Conecta',    d:'Relaciona variables y sistemas, contrasta datos y selecciona modelos con mayor autonomía.' },
    { id:10, t:'Transfiere', d:'Modela cuantitativamente, evalúa límites y llega a Bachillerato con prerrequisitos explícitos de Física.' }
  ]
};

/* ---------- Unidades (18): reto, destrezas AO, indicadores, saberes, evidencia, APV y trazabilidad ---------- */
const UCN = (grado, dom, n, t, reto, destrezas, indicadores, saberes, evidencia, instrumento, apv, traza, recursos) =>
  ({ id:`${grado}-${dom}-${n}`, grado, dom, n, t, reto, destrezas, indicadores, saberes, evidencia, instrumento, apv, traza, recursos });
const DZ = (c, pri, niv, d) => ({ c, pri, niv, d });

BIO.cn.unidades = [
  /* ================= 8.º · CIENCIAS DE LA VIDA Y LA TIERRA ================= */
  UCN(8,'cvt',1,'La célula, organización y reproducción',
    '¿Cómo pasa una célula a formar un organismo capaz de crecer, regularse y reproducirse?',
    [ DZ('AO.CVT.8.01','IMPRESCINDIBLE','N1','Reconocer estructuras celulares y relacionarlas con funciones mediante imágenes, modelos y observaciones.'),
      DZ('AO.CVT.8.02','IMPRESCINDIBLE','N2','Explicar niveles de organización biológica y comparar reproducción sexual y asexual atendiendo continuidad y variación.'),
      DZ('AO.CVT.8.03','DESEABLE','N3','Evaluar evidencia microscópica o simulada y modelar cómo una alteración local puede afectar al sistema.') ],
    [ 'Identifica estructuras y funciones sin confundir modelo con observación.',
      'Relaciona célula, tejido, órgano y sistema y explica el sentido biológico de la reproducción.',
      'Distingue evidencia, inferencia y limitación y formula una explicación revisable.' ],
    'Teoría celular; procariota y eucariota; organelos; tejido, órgano y sistema; homeostasis inicial; reproducción; variación.',
    'Atlas sistémico de la vida con escala, relaciones estructura-función y escenario de alteración.',
    'Rúbrica de modelación biológica + bitácora de evidencia',
    'Interpretar imágenes y explicaciones sobre el cuerpo y otros seres vivos sin convertir modelos en diagnósticos.',
    'CN.4.1.3–9; CE.CN.4.1–2',
    ['celula','microscopio']),
  UCN(8,'cvt',2,'Ecosistemas, energía, ciclos y biodiversidad',
    '¿Qué cambia en un ecosistema cuando se modifica una población, un recurso o una condición ambiental?',
    [ DZ('AO.CVT.8.04','IMPRESCINDIBLE','N1','Construir cadenas y redes tróficas e identificar productores, consumidores y descomponedores.'),
      DZ('AO.CVT.8.05','IMPRESCINDIBLE','N2','Explicar el flujo de energía y los ciclos de materia mediante modelos complementarios y datos sencillos.'),
      DZ('AO.CVT.8.06','DESEABLE','N3','Predecir efectos directos e indirectos de una perturbación y evaluar una medida de conservación.') ],
    [ 'Representa correctamente la dirección de transferencia de materia y energía.',
      'Distingue lo que fluye de lo que se recicla y conecta escalas ecológicas.',
      'Sustenta predicciones y reconoce incertidumbre antes de recomendar una acción.' ],
    'Ecosistema; nicho; niveles tróficos; productividad; ciclos; perturbación; biodiversidad; conservación.',
    'Estudio de caso de un ecosistema ecuatoriano con red, escenario de cambio y recomendación.',
    'Rúbrica causal + mapa de sistema revisado por pares',
    'Anticipar consecuencias antes de alterar componentes de un sistema natural.',
    'CN.4.1.10–12; CN.4.4.7–8; CE.CN.4.3',
    ['eco-red']),
  UCN(8,'cvt',3,'Tierra, atmósfera, clima y riesgo',
    '¿Cómo conectamos procesos de la Tierra y la atmósfera con datos de clima y decisiones de prevención?',
    [ DZ('AO.CVT.8.07','IMPRESCINDIBLE','N1','Diferenciar tiempo atmosférico y clima mediante variables, escalas y series de datos.'),
      DZ('AO.CVT.8.08','IMPRESCINDIBLE','N2','Explicar relaciones entre radiación, atmósfera, océano, relieve y patrones climáticos del Ecuador.'),
      DZ('AO.CVT.8.09','DESEABLE','N3','Interpretar una alerta y comunicar riesgo distinguiendo peligro, exposición y vulnerabilidad.') ],
    [ 'Clasifica afirmaciones y utiliza unidades y periodos pertinentes.',
      'Construye un modelo causal con más de una variable.',
      'Cita fuentes oficiales y propone una respuesta proporcional al riesgo.' ],
    'Tiempo; clima; radiación; atmósfera; océano; relieve; El Niño; amenaza; exposición; vulnerabilidad.',
    'Boletín de clima y riesgo con serie de datos, explicación causal y protocolo de actuación.',
    'Rúbrica de datos ambientales + verificación de fuentes',
    'Interpretar pronósticos y alertas sin alarmismo y actuar con información oficial.',
    'CN.4.4.6, 10–11; inserción EDS',
    ['clima']),

  /* ================= 8.º · CIENCIAS FÍSICAS ================= */
  UCN(8,'cf',1,'Medir la materia: masa, volumen, densidad y presión',
    '¿Qué mediciones permiten explicar por qué materiales y objetos se comportan de manera diferente?',
    [ DZ('AO.CF.8.01','IMPRESCINDIBLE','N1','Diferenciar masa, volumen, densidad y presión usando unidades, instrumentos y representaciones pertinentes.'),
      DZ('AO.CF.8.02','IMPRESCINDIBLE','N2','Determinar densidad o presión con datos experimentales o simulados y analizar precisión y errores.'),
      DZ('AO.CF.8.03','DESEABLE','N3','Diseñar una solución de flotación, soporte o distribución de carga y justificarla con evidencia.') ],
    [ 'Mide o interpreta datos y controla unidades y orden de magnitud.',
      'Calcula, grafica y explica la relación entre variables.',
      'El diseño conecta propiedades, datos, seguridad y mejora iterativa.' ],
    'Propiedades de la materia; masa; volumen; densidad; presión; medición; error; flotación; seguridad.',
    'Informe experimental o simulación con datos, gráfico, explicación y rediseño.',
    'Rúbrica de indagación + lista de cotejo metrológica',
    'Elegir materiales y distribuir cargas a partir de propiedades medibles.',
    'CN.4.3.9, 12; CE.CN.4.9',
    ['lab-densidad']),
  UCN(8,'cf',2,'Movimiento, fuerzas y energía',
    '¿Cómo pasamos de describir un movimiento a explicar qué interacción lo cambia?',
    [ DZ('AO.CF.8.04','IMPRESCINDIBLE','N1','Describir posición, trayectoria, distancia, desplazamiento y rapidez en un marco de referencia.'),
      DZ('AO.CF.8.05','IMPRESCINDIBLE','N2','Relacionar fuerzas equilibradas o no equilibradas, fricción y masa con cambios de movimiento y energía.'),
      DZ('AO.CF.8.06','DESEABLE','N3','Investigar una variable que modifica el movimiento y evaluar la calidad del diseño experimental.') ],
    [ 'Interpreta tablas y gráficos sin confundir distancia con desplazamiento.',
      'Construye diagramas de fuerza y explica el efecto de la resultante.',
      'Controla variables, repite mediciones y limita la explicación a los datos.' ],
    'Marco de referencia; desplazamiento; rapidez; fuerza neta; masa; fricción; energía cinética y potencial; variable.',
    'Investigación con carrito, video, datos provistos o simulador con modelo y defensa.',
    'Rúbrica de prácticas científicas + gráfico anotado',
    'Analizar movimiento, energía y riesgo antes de tomar decisiones de seguridad.',
    'CN.4.3.1, 3, 5, 8; CE.CN.4.8',
    ['lab-movimiento']),
  UCN(8,'cf',3,'Energía y transferencia: calor, luz y sonido',
    '¿Cómo reconocemos una transferencia de energía y qué representación permite explicar sus efectos?',
    [ DZ('AO.CF.8.07','IMPRESCINDIBLE','N1','Distinguir temperatura, calor y transferencia de energía mediante mediciones o datos proporcionados.'),
      DZ('AO.CF.8.08','IMPRESCINDIBLE','N2','Explicar transformaciones de energía en situaciones térmicas, luminosas y sonoras mediante diagramas y balances cualitativos.'),
      DZ('AO.CF.8.09','DESEABLE','N3','Explorar amplitud, frecuencia y atenuación en una simulación de ondas y justificar una aplicación segura.') ],
    [ 'Diferencia sensación, temperatura y calor y reconoce el mecanismo de transferencia.',
      'Identifica entrada, transformación, efecto útil y pérdidas.',
      'Interpreta una gráfica de onda y relaciona cambios de parámetros con el fenómeno.' ],
    'Temperatura; calor; conducción, convección y radiación; energía; luz y sonido; amplitud; frecuencia; seguridad.',
    'Laboratorio virtual de transferencia y ondas con predicción, datos, explicación y aplicación.',
    'Rúbrica de modelización física + registro de simulación',
    'Evaluar aislamiento, iluminación y comunicación sonora con criterios físicos y de bienestar.',
    'Consolidación CN.3.3.5–12; profundización institucional de CN.4.3',
    ['energia']),

  /* ================= 9.º · CIENCIAS DE LA VIDA Y LA TIERRA ================= */
  UCN(9,'cvt',1,'Herencia, evolución y diversidad',
    '¿Cómo explican genes, variación y selección natural la continuidad y el cambio de la vida?',
    [ DZ('AO.CVT.9.01','IMPRESCINDIBLE','N1','Relacionar ADN, genes, cromosomas, mitosis y meiosis con continuidad biológica y variación.'),
      DZ('AO.CVT.9.02','IMPRESCINDIBLE','N2','Explicar selección natural con variación heredable, presión ambiental y reproducción diferencial.'),
      DZ('AO.CVT.9.03','DESEABLE','N3','Evaluar una afirmación sobre herencia o evolución usando evidencia y lenguaje no determinista.') ],
    [ 'Diferencia procesos celulares y su producto.',
      'Conecta mecanismo y cambio poblacional sin atribuir intención a la evolución.',
      'Contrasta evidencias y corrige generalizaciones no sustentadas.' ],
    'ADN; gen; cromosoma; mitosis; meiosis; variación; selección natural; adaptación; fósiles; ancestro común.',
    'Expediente de evidencia que conecta herencia, variación y cambio evolutivo.',
    'Rúbrica CER + ficha de lenguaje y evidencia',
    'Distinguir probabilidad biológica de determinismo y evaluar explicaciones por su evidencia.',
    'CN.4.1.6, 8, 14, 16; CN.4.4.15; CE.CN.4.2, 5',
    ['herencia','celula']),
  UCN(9,'cvt',2,'Sistemas humanos, reproducción, inmunidad y salud',
    '¿Cómo se coordinan sistemas del cuerpo y qué evidencia permite tomar decisiones de salud responsables?',
    [ DZ('AO.CVT.9.04','IMPRESCINDIBLE','N1','Explicar reproducción humana y coordinación de sistemas usando terminología científica y respetuosa.'),
      DZ('AO.CVT.9.05','IMPRESCINDIBLE','N2','Modelar barreras, respuesta inmunitaria y vacunación y diferenciar virus, bacterias y tratamientos.'),
      DZ('AO.CVT.9.06','DESEABLE','N3','Evaluar una afirmación sanitaria y resolver un caso ficticio integrando evidencia, consentimiento y búsqueda de ayuda.') ],
    [ 'Organiza procesos sin convertir la clase en diagnóstico personal.',
      'Relaciona mecanismo, prevención y límites de tratamientos.',
      'Consulta fuentes autorizadas y formula una decisión prudente y no estigmatizante.' ],
    'Reproducción; sistemas corporales; virus; bacterias; inmunidad; vacunas; antibióticos; prevención; consentimiento.',
    'Guía de salud basada en casos ficticios y verificación de una afirmación pública.',
    'Rúbrica de explicación y riesgo + auditoría de fuentes',
    'Buscar apoyo y fuentes confiables para decisiones de salud sin exponer información privada.',
    'CN.4.2.1–3, 5, 7; CN.4.5.6; CE.CN.4.7',
    ['corazon','pulmones','cerebro','sim-circulacion']),
  UCN(9,'cvt',3,'Biodiversidad del Ecuador y conservación',
    '¿Cómo priorizamos una acción de conservación con evidencia ecológica y justicia territorial?',
    [ DZ('AO.CVT.9.07','IMPRESCINDIBLE','N1','Caracterizar ecosistemas ecuatorianos por clima, biodiversidad, servicios y amenazas.'),
      DZ('AO.CVT.9.08','IMPRESCINDIBLE','N2','Analizar áreas protegidas y otras estrategias de conservación mediante evidencia ecológica y social.'),
      DZ('AO.CVT.9.09','DESEABLE','N3','Diseñar una acción viable con indicador, actores, riesgos y mecanismo de seguimiento.') ],
    [ 'Relaciona condiciones y especies sin generalizar entre regiones.',
      'Contrasta beneficios, límites y posibles conflictos de una estrategia.',
      'La propuesta incluye indicador, factibilidad y respeto a comunidades vinculadas.' ],
    'Biodiversidad; endemismo; servicios ecosistémicos; áreas protegidas; restauración; indicador; justicia territorial.',
    'Ficha de decisión para una estrategia de conservación con mapa y tablero de indicadores.',
    'Rúbrica de decisión socioecológica + revisión de factibilidad',
    'Participar en acciones ambientales medibles y pertinentes al territorio.',
    'CN.4.1.17–18; CN.4.4.13; CN.4.5.5; inserción EDS',
    ['eco-red']),

  /* ================= 9.º · CIENCIAS FÍSICAS ================= */
  UCN(9,'cf',1,'Cinemática: cambio, aceleración y gráficas',
    '¿Qué información aportan las gráficas de movimiento y cuándo un modelo deja de describir los datos?',
    [ DZ('AO.CF.9.01','IMPRESCINDIBLE','N1','Representar posición y velocidad en tablas y gráficas y reconocer cambios de movimiento.'),
      DZ('AO.CF.9.02','IMPRESCINDIBLE','N2','Interpretar pendiente, variación y aceleración en movimientos rectilíneos usando relaciones cuantitativas accesibles.'),
      DZ('AO.CF.9.03','DESEABLE','N3','Comparar un modelo de movimiento con datos y explicar discrepancias, errores y límites.') ],
    [ 'Conecta ejes, unidades y significado físico.',
      'Calcula razones de cambio y distingue velocidad de aceleración.',
      'Contrasta predicción y datos y propone una mejora del modelo o procedimiento.' ],
    'Posición; desplazamiento; velocidad; aceleración; pendiente; tablas; gráficos; modelo; discrepancia; incertidumbre.',
    'Videoanálisis o conjunto de datos de movimiento con gráficos, modelo y conclusión.',
    'Rúbrica de modelación + lista de lectura de gráficas',
    'Interpretar datos de movilidad y detectar conclusiones físicamente incoherentes.',
    'CN.4.3.1, 3, 5, 8; CE.CN.4.8',
    ['lab-movimiento']),
  UCN(9,'cf',2,'Electricidad, circuitos y energía',
    '¿Cómo explica un circuito el transporte y la transformación de energía sin usar electricidad peligrosa?',
    [ DZ('AO.CF.9.04','IMPRESCINDIBLE','N1','Distinguir corriente, diferencia de potencial, conductores y aislantes en circuitos de baja tensión o simulados.'),
      DZ('AO.CF.9.05','IMPRESCINDIBLE','N2','Comparar circuitos simples en serie y paralelo mediante datos, diagramas y transformaciones de energía.'),
      DZ('AO.CF.9.06','DESEABLE','N3','Evaluar consumo o funcionamiento de un dispositivo mediante potencia, tiempo de uso y criterios de seguridad.') ],
    [ 'Interpreta diagramas y no confunde corriente con energía.',
      'Predice cambios al modificar una conexión y contrasta con datos.',
      'Formula una recomendación sustentada sin manipular instalaciones domésticas.' ],
    'Circuito; corriente; voltaje; resistencia cualitativa; serie; paralelo; potencia; energía; seguridad eléctrica.',
    'Circuito virtual + auditoría energética de un escenario ficticio con recomendación.',
    'Rúbrica de explicación eléctrica + protocolo de seguridad',
    'Comprender consumo y funcionamiento de dispositivos sin exponer datos económicos ni manipular la red.',
    'Consolidación CN.3.3.9–12; profundización institucional hacia Física de Bachillerato',
    ['lab-circuitos']),
  UCN(9,'cf',3,'Gravedad, radiación y modelos del espacio',
    '¿Cómo explican los modelos el movimiento celeste y qué información aportan distintas radiaciones?',
    [ DZ('AO.CF.9.07','IMPRESCINDIBLE','N1','Relacionar gravedad, masa, distancia y órbitas en modelos del sistema solar.'),
      DZ('AO.CF.9.08','IMPRESCINDIBLE','N2','Interpretar el espectro electromagnético por longitud de onda, energía, usos y riesgos.'),
      DZ('AO.CF.9.09','DESEABLE','N3','Comparar datos o modelos astronómicos y explicar cómo nueva evidencia modifica una explicación.') ],
    [ 'Explica órbitas sin confundir escala del modelo con tamaño real.',
      'Ordena regiones del espectro y argumenta medidas de uso seguro.',
      'Vincula instrumento, dato, inferencia y límite del conocimiento.' ],
    'Gravedad; órbita; escala; sistema solar; espectro electromagnético; radiación; instrumento; evidencia indirecta.',
    'Exposición interactiva de una misión o instrumento y la evidencia física que produce.',
    'Rúbrica de modelación científica + explicación oral',
    'Interpretar información sobre satélites, radiación y tecnologías de comunicación.',
    'CN.4.3.14–15; CN.4.4.3–6; CE.CN.4.12',
    ['sim-espacio']),

  /* ================= 10.º · CIENCIAS DE LA VIDA Y LA TIERRA ================= */
  UCN(10,'cvt',1,'Biomoléculas, regulación y homeostasis',
    '¿Cómo conectan la estructura molecular, la función y la regulación de los sistemas vivos?',
    [ DZ('AO.CVT.10.01','IMPRESCINDIBLE','N1','Relacionar carbohidratos, lípidos, proteínas y ácidos nucleicos con funciones biológicas.'),
      DZ('AO.CVT.10.02','IMPRESCINDIBLE','N2','Explicar homeostasis integrando regulación nerviosa, hormonal y respuestas de distintos sistemas.'),
      DZ('AO.CVT.10.03','DESEABLE','N3','Evaluar una afirmación sobre nutrición o funcionamiento corporal distinguiendo evidencia, marketing y extrapolación.') ],
    [ 'Construye comparaciones estructura-función con vocabulario correcto.',
      'Explica retroalimentación y coordinación sistémica sin convertirla en diagnóstico.',
      'Formula una conclusión prudente y cita fuentes de salud pertinentes.' ],
    'Biomoléculas; estructura-función; homeostasis; regulación; sistemas; evidencia nutricional; fuente de salud.',
    'Expediente de explicación sistémica y verificación de una afirmación de salud.',
    'Rúbrica de explicación biológica + protocolo de fuentes',
    'Interpretar mensajes sobre nutrición y salud con criterio y límites.',
    'CN.4.3.16, 18; CE.CN.4.11; integración CN.4.2',
    ['biomoleculas','corazon','celula']),
  UCN(10,'cvt',2,'Tierra dinámica, océanos y cambio climático',
    '¿Cómo conectan procesos internos, ciclos planetarios y océanos con riesgos y cambios observables?',
    [ DZ('AO.CVT.10.04','IMPRESCINDIBLE','N1','Relacionar placas, bordes, sismos, vulcanismo y ciclo de rocas mediante modelos geológicos.'),
      DZ('AO.CVT.10.05','IMPRESCINDIBLE','N2','Analizar ciclos de carbono y agua y datos climáticos u oceánicos separando variabilidad y tendencia.'),
      DZ('AO.CVT.10.06','DESEABLE','N3','Comparar medidas de mitigación y adaptación por impacto, equidad, costo y factibilidad.') ],
    [ 'Reconstruye procesos y evita confundir corteza con placa.',
      'Distingue reservorios, flujos y escalas temporales.',
      'Prioriza con indicador y reconoce compensaciones.' ],
    'Tectónica; ciclo de rocas; océano; ciclos biogeoquímicos; efecto invernadero; tendencia; mitigación; adaptación.',
    'Tablero geoclimático con mapa, serie de datos y matriz de decisión.',
    'Rúbrica geocientífica y de datos + auditoría de fuentes',
    'Usar información oficial para prevención y decisiones climáticas medibles.',
    'CN.4.4.7–11, 16–17; CE.CN.4.14; inserción EDS',
    ['tierra','clima']),
  UCN(10,'cvt',3,'Decisiones sociocientíficas y sostenibilidad',
    '¿Cómo decidimos cuando la ciencia informa, pero también intervienen valores, costos, derechos e incertidumbre?',
    [ DZ('AO.CVT.10.07','IMPRESCINDIBLE','N1','Delimitar una cuestión sociocientífica y diferenciar hechos, incertidumbres, valores e intereses.'),
      DZ('AO.CVT.10.08','IMPRESCINDIBLE','N2','Evaluar alternativas mediante evidencia científica, consecuencias, equidad y principio de precaución.'),
      DZ('AO.CVT.10.09','DESEABLE','N3','Diseñar y defender una recomendación revisable con indicador, salvaguarda y plan de comunicación.') ],
    [ 'Construye un mapa del problema, actores y evidencia.',
      'Aplica criterios consistentes y reconoce compensaciones.',
      'La recomendación es viable, transparente y proporcional a la evidencia.' ],
    'Cuestión sociocientífica; actor; evidencia; valor; riesgo; precaución; equidad; monitoreo; sostenibilidad.',
    'Audiencia científica simulada sobre agua, biodiversidad, salud o clima con resolución.',
    'Rúbrica de decisión + dossier de evidencia + defensa individual',
    'Participar en decisiones públicas informadas sin convertir la ciencia en autoridad única.',
    'Integración CN.4.1–5; inserciones EDS y socioemocional',
    ['eco-red','audiencia']),

  /* ================= 10.º · CIENCIAS FÍSICAS ================= */
  UCN(10,'cf',1,'Cinemática cuantitativa y modelización',
    '¿Cómo describimos un movimiento con datos y decidimos si un modelo representa realmente lo observado?',
    [ DZ('AO.CF.10.01','IMPRESCINDIBLE','N1','Representar posición, velocidad y aceleración mediante tablas, gráficos, vectores básicos y unidades coherentes.'),
      DZ('AO.CF.10.02','IMPRESCINDIBLE','N2','Resolver movimientos rectilíneos y analizar pendientes, cambios y áreas cualitativas en representaciones múltiples.'),
      DZ('AO.CF.10.03','DESEABLE','N3','Contrastar un modelo cinemático con datos, estimar incertidumbre y justificar cuándo necesita revisión.') ],
    [ 'Conecta cada representación con el fenómeno y sus unidades.',
      'Resuelve, estima y verifica sin depender de una fórmula aislada.',
      'Examina discrepancias y declara supuestos y límites.' ],
    'Sistema de referencia; vector básico; velocidad; aceleración; pendiente; representación x-t y v-t; estimación; incertidumbre.',
    'Informe de videoanálisis o datos simulados con modelo, verificación y predicción.',
    'Rúbrica de modelación cuantitativa + defensa técnica',
    'Leer y cuestionar datos de movilidad, rendimiento y seguridad.',
    'CN.4.3.1–8; CE.CN.4.8; articulación vertical con CN.F.5.1',
    ['lab-movimiento']),
  UCN(10,'cf',2,'Dinámica, trabajo, energía e impulso',
    '¿Cómo usamos fuerzas y balances para explicar cambios y diseñar medidas de seguridad?',
    [ DZ('AO.CF.10.04','IMPRESCINDIBLE','N1','Construir diagramas de fuerzas y relacionar fuerza neta, masa y aceleración en situaciones de una y dos dimensiones sencillas.'),
      DZ('AO.CF.10.05','IMPRESCINDIBLE','N2','Relacionar trabajo, energía, potencia e impulso con cambios observables y comprobar resultados mediante balances.'),
      DZ('AO.CF.10.06','DESEABLE','N3','Evaluar una medida de seguridad o diseño mediante datos, restricciones y una variación del caso.') ],
    [ 'Delimita el sistema, representa interacciones y conserva signos y unidades.',
      'Distingue transferencia de energía, potencia e impulso y verifica plausibilidad.',
      'Formula una recomendación proporcional y modifica su desempeño ante un dato nuevo.' ],
    'Fuerza neta; masa; fricción; trabajo; energía cinética y potencial; potencia; impulso; cantidad de movimiento; sistema.',
    'Caso de seguridad o transporte con diagramas, balance, datos y defensa.',
    'Rúbrica de modelos físicos + matriz de decisión',
    'Justificar decisiones de movilidad y protección mediante modelos, no por intuición.',
    'Profundización CN.4.3 y articulación vertical con CN.F.5.1–2',
    ['lab-movimiento']),
  UCN(10,'cf',3,'Electricidad, magnetismo y ondas: puente a Bachillerato',
    '¿Cómo conectamos circuitos, campos y señales para explicar tecnologías cotidianas sin convertirlas en una caja negra?',
    [ DZ('AO.CF.10.07','IMPRESCINDIBLE','N1','Analizar circuitos simples mediante corriente, voltaje, resistencia, potencia y transformaciones de energía.'),
      DZ('AO.CF.10.08','IMPRESCINDIBLE','N2','Relacionar corriente y magnetismo y explicar cualitativamente inducción, motores o generadores mediante energía y campo.'),
      DZ('AO.CF.10.09','DESEABLE','N3','Interpretar ondas y señales por amplitud, frecuencia, longitud de onda y rapidez y evaluar una aplicación de comunicación.') ],
    [ 'Interpreta serie/paralelo y verifica coherencia de potencia y energía.',
      'Predice un cambio al modificar corriente, movimiento relativo o configuración.',
      'Lee gráficas de ondas y justifica una decisión de comunicación o control.' ],
    'Voltaje; corriente; resistencia; potencia; campo magnético; inducción; motor; generador; onda; frecuencia; longitud de onda.',
    'Sistema virtual de energía o comunicación con circuito, señal, explicación y prueba de una condición nueva.',
    'Rúbrica de modelización + defensa de autoría y seguridad',
    'Comprender consumo, control y comunicación tecnológica con criterios físicos y de seguridad.',
    'Consolidación CN.3.3.9–12; articulación vertical con CN.F.5.1 y CN.F.5.3',
    ['lab-circuitos','sim-espectro'])
];
BIO.cnUnidad = id => BIO.cn.unidades.find(u => u.id === id);
BIO.cnUnidadesDe = (grado, dom) => BIO.cn.unidades.filter(u => u.grado === +grado && (!dom || u.dom === dom));

/* ---------- Recursos de Ciencias Naturales ---------- */
BIO.cn.recursos = {
  'lab-densidad':   { t:'Laboratorio 3D: densidad y flotación', tipo:'Laboratorio 3D', em:'⚖️', href:'#/cn/lab/densidad', ok:true, act:'cn-lab-densidad',
    d:'Pesa, mide volumen por desplazamiento, calcula densidad y predice si flota en seis líquidos distintos.',
    reto:'Encuentra un líquido en el que el aluminio flote y explica por qué flotar no depende de ser liviano.' },
  'lab-movimiento': { t:'Laboratorio 3D: movimiento, fuerzas y energía', tipo:'Laboratorio 3D', em:'🛷', href:'#/cn/lab/movimiento', ok:true, act:'cn-lab-movimiento',
    d:'Pista con carrito, sensores, rampa y gravedad de otros mundos; gráficas x-t, v-t y a-t en vivo y diagrama de fuerzas.',
    reto:'Consigue que el carrito recorra 2,0 m en exactamente 2,0 s partiendo del reposo.' },
  'lab-circuitos':  { t:'Laboratorio 3D: electricidad y circuitos', tipo:'Laboratorio 3D', em:'💡', href:'#/cn/lab/circuitos', ok:true, act:'cn-lab-circuitos',
    d:'Arma circuitos en serie, paralelo y mixtos; mide con amperímetro y voltímetro y calcula el consumo del hogar.',
    reto:'Haz que dos focos brillen igual de fuerte que uno solo y explica por qué.' },
  'sim-espacio':    { t:'Simulador 3D: sistema solar y espectro', tipo:'Simulador 3D', em:'🪐', href:'#/cn/sim/espacio', ok:true, act:'cn-sim-espacio',
    d:'Órbitas a dos escalas, tiempo acelerado, tu peso en cada planeta y el espectro electromagnético con usos y riesgos.',
    reto:'Descubre la relación entre la distancia al Sol y la duración del año de cada planeta.' },
  'sim-espectro':   { t:'Espectro electromagnético', tipo:'Simulador', em:'🌈', href:'#/cn/sim/espectro', ok:true, act:'cn-sim-espacio',
    d:'De las ondas de radio a los rayos gamma: longitud de onda, energía, usos cotidianos y protección.',
    reto:'Ordena las regiones por energía y justifica qué protección necesita cada una.' },
  'eco-red':        { t:'Ecosistemas del Ecuador: red trófica y perturbaciones', tipo:'Simulador', em:'🌳', href:'#/cn/eco/red-trofica', ok:true, act:'cn-eco-red',
    d:'Páramo, manglar y Amazonía: construye la red, mide el flujo de energía y simula una perturbación a 36 años.',
    reto:'Predice qué pasa con cada población cuando desaparece el depredador tope y compruébalo.' },
  'celula':         { t:'Célula animal en 3D', tipo:'Modelo 3D', em:'🔬', href:'#/explorar/celula', ok:true, act:'reto-celula',
    d:'Organelos en corte, "ver en acción" y vista en detalle de cada estructura.',
    reto:'Explica cómo colaboran núcleo, retículo, Golgi y mitocondria para fabricar y exportar una proteína.' },
  'corazon':        { t:'Corazón humano en 3D', tipo:'Modelo 3D', em:'🫀', href:'#/explorar/corazon', ok:true, act:'reto-corazon',
    d:'Cámaras, válvulas animadas y flujo sanguíneo; útil para la coordinación de sistemas.',
    reto:'Explica cómo el corazón mantiene separadas las dos circulaciones.' },
  'pulmones':       { t:'Pulmones y vía aérea en 3D', tipo:'Modelo 3D', em:'🫁', href:'#/explorar/pulmones', ok:true, act:'reto-pulmones',
    d:'Árbol bronquial, diafragma y lupa de alvéolos con intercambio gaseoso.',
    reto:'Sigue el recorrido del aire y explica dónde ocurre el intercambio de gases.' },
  'cerebro':        { t:'Cerebro en 3D', tipo:'Modelo 3D', em:'🧠', href:'#/explorar/cerebro', ok:true, act:'reto-cerebro',
    d:'Lóbulos, cerebelo, estructuras profundas e impulso nervioso.',
    reto:'Relaciona cada región del encéfalo con la función que controla.' },
  'sim-circulacion':{ t:'Simulador cardiorrespiratorio', tipo:'Simulador', em:'∿', href:'#/simuladores/circulacion', ok:true, act:'reto-simulador',
    d:'Actividad física, ventilación, anemia y altitud: cómo se ajustan corazón y pulmones.',
    reto:'Encuentra la ventilación mínima que cubre la demanda de oxígeno al 80 % de actividad.' },
  'microscopio':    { t:'Microscopio virtual', tipo:'Microscopio', em:'🔎', href:'#/microscopio', ok:true,
    d:'Muestras de tejidos, sangre y microorganismos con aumentos de 4x a 100x.', reto:'Identifica el tejido por la forma y organización de sus células.' },
  'herencia':       { t:'Constructor de cruces y ADN 3D', tipo:'Laboratorio', em:'🧬', href:'#/explorar/genetica', ok:true,
    d:'Gametos, cuadro de Punnett, probabilidades y mutaciones.', reto:'Predice la proporción de fenotipos de un cruce y compruébala.' },
  'clima':          { t:'Tablero de clima y riesgo del Ecuador', tipo:'Tablero de datos', em:'🌦️', href:'#/cn/clima', ok:true,
    d:'Series de temperatura y lluvia, El Niño, amenaza, exposición y vulnerabilidad.', reto:'Interpreta una alerta y propone una respuesta proporcional.' },
  'energia':        { t:'Laboratorio de calor, luz y sonido', tipo:'Laboratorio 3D', em:'🔥', href:'#/cn/lab/energia', ok:true,
    d:'Conducción, convección y radiación; ondas con amplitud y frecuencia.', reto:'Identifica entrada, transformación, efecto útil y pérdidas.' },
  'biomoleculas':   { t:'Biomoléculas 3D y homeostasis', tipo:'Modelo 3D', em:'🧪', href:'#/cn/biomoleculas', ok:true,
    d:'Carbohidratos, lípidos, proteínas y ácidos nucleicos; retroalimentación hormonal.', reto:'Explica una regulación por retroalimentación negativa.' },
  'tierra':         { t:'Tierra dinámica: placas y ciclo de rocas', tipo:'Modelo 3D', em:'🌋', href:'#/cn/tierra', ok:true,
    d:'Placas, bordes, sismos, vulcanismo y ciclo de rocas del Ecuador.', reto:'Reconstruye el proceso que originó un sismo en la costa ecuatoriana.' },
  'audiencia':      { t:'Audiencia científica simulada', tipo:'Caso', em:'⚖️', href:'#/cn/audiencia', ok:true,
    d:'Agua, biodiversidad, salud o clima: actores, evidencia, valores y resolución.', reto:'Defiende una recomendación revisable con indicador y salvaguarda.' }
};
BIO.cnRecurso = id => Object.assign({ id }, BIO.cn.recursos[id] || {});

/* ---------- Actividades de Ciencias Naturales (progreso y calificación) ---------- */
BIO.cnGradeItems = [
  { id:'cn-lab-densidad',   t:'Laboratorio: densidad y flotación', corto:'Densidad', unidad:'8-cf-1', tipo:'Laboratorio', peso:3 },
  { id:'cn-lab-movimiento', t:'Laboratorio: movimiento y fuerzas', corto:'Movimiento', unidad:'8-cf-2', tipo:'Laboratorio', peso:3 },
  { id:'cn-eco-red',        t:'Ecosistemas: red trófica y perturbación', corto:'Red trófica', unidad:'8-cvt-2', tipo:'Simulador', peso:3 },
  { id:'reto-celula',       t:'Reto: la célula', corto:'Célula 3D', unidad:'8-cvt-1', tipo:'Reto', peso:2 },
  { id:'cn-lab-circuitos',  t:'Laboratorio: electricidad y circuitos', corto:'Circuitos', unidad:'9-cf-2', tipo:'Laboratorio', peso:3 },
  { id:'cn-sim-espacio',    t:'Simulador: sistema solar y espectro', corto:'Espacio', unidad:'9-cf-3', tipo:'Simulador', peso:3 },
  { id:'reto-corazon',      t:'Reto: el corazón', corto:'Corazón', unidad:'9-cvt-2', tipo:'Reto', peso:2 },
  { id:'reto-pulmones',     t:'Reto: los pulmones', corto:'Pulmones', unidad:'9-cvt-2', tipo:'Reto', peso:2 },
  { id:'reto-cerebro',      t:'Reto: el cerebro', corto:'Cerebro', unidad:'9-cvt-2', tipo:'Reto', peso:2 },
  /* --- módulos incorporados en v1.0 y v1.1 --- */
  { id:'cn-lab-energia',    t:'Laboratorio: calor, luz y sonido', corto:'Energía', unidad:'8-cf-3', tipo:'Laboratorio', peso:3 },
  { id:'reto-microscopio',  t:'Microscopio virtual', corto:'Microscopio', unidad:'8-cvt-1', tipo:'Reto', peso:2 },
  { id:'reto-celula-vegetal', t:'Reto: la célula vegetal', corto:'Cél. vegetal', unidad:'8-cvt-1', tipo:'Reto', peso:2 },
  { id:'reto-procesos',     t:'Reto: procesos celulares', corto:'Procesos', unidad:'8-cvt-1', tipo:'Reto', peso:2 },
  { id:'reto-adn',          t:'Reto: ADN y mutaciones', corto:'ADN', unidad:'9-cvt-1', tipo:'Reto', peso:2 },
  { id:'reto-cruces',       t:'Reto: cuadro de Punnett', corto:'Cruces', unidad:'9-cvt-1', tipo:'Reto', peso:2 },
  { id:'cn-clima',          t:'Tablero de clima y riesgo', corto:'Clima', unidad:'9-cvt-3', tipo:'Tablero', peso:3 },
  { id:'cn-tierra',         t:'Tierra dinámica', corto:'Tierra', unidad:'10-cvt-2', tipo:'Modelo 3D', peso:3 },
  { id:'cn-biomoleculas',   t:'Biomoléculas y homeostasis', corto:'Biomoléculas', unidad:'10-cvt-1', tipo:'Laboratorio', peso:3 },
  { id:'cn-audiencia',      t:'Audiencia científica simulada', corto:'Audiencia', unidad:'10-cvt-3', tipo:'Caso', peso:4 }
];
/* Registro autoritativo de las actividades de Ciencias Naturales (sin unidad de Biología: no afectan ese progreso) */
BIO.cnActividades = {
  'cn-lab-densidad':   { t:'Laboratorio: densidad y flotación', unidad:null, peso:0, xp:120 },
  'cn-lab-movimiento': { t:'Laboratorio: movimiento, fuerzas y energía', unidad:null, peso:0, xp:140 },
  'cn-lab-circuitos':  { t:'Laboratorio: electricidad y circuitos', unidad:null, peso:0, xp:120 },
  'cn-sim-espacio':    { t:'Simulador: sistema solar y espectro', unidad:null, peso:0, xp:120 },
  'cn-eco-red':        { t:'Ecosistemas: red trófica y perturbaciones', unidad:null, peso:0, xp:140 },
  'cn-lab-energia':    { t:'Laboratorio: calor, luz y sonido', unidad:null, peso:0, xp:140 },
  'cn-clima':          { t:'Tablero de clima y riesgo del Ecuador', unidad:null, peso:0, xp:120 },
  'cn-tierra':         { t:'Tierra dinámica: placas, sismos y volcanes', unidad:null, peso:0, xp:140 },
  'reto-microscopio':  { t:'Microscopio virtual', unidad:null, peso:0, xp:100 },
  'cn-biomoleculas':   { t:'Biomoléculas y homeostasis', unidad:null, peso:0, xp:140 },
  'cn-audiencia':      { t:'Audiencia científica simulada', unidad:null, peso:0, xp:150 }
};
Object.assign(BIO.activities, BIO.cnActividades);
BIO.cnItemsDe = grado => BIO.cnGradeItems.filter(i => +String(i.unidad).split('-')[0] === +grado);
</script>
